sudo: false
language: go
go:
  - 1.8.x
install:
  - GLIDE_OS_ARCH=`go env GOHOSTOS`-`go env GOHOSTARCH`
  - GLIDE_TAG=v0.12.3
  - GLIDE_LATEST_RELEASE_URL="https://github.com/Masterminds/glide/releases/download/${GLIDE_TAG}/glide-${GLIDE_TAG}-${GLIDE_OS_ARCH}.tar.gz"
  - wget ${GLIDE_LATEST_RELEASE_URL} -O /tmp/glide.tar.gz
  - mkdir /tmp/glide
  - tar --directory=/tmp/glide -xvf /tmp/glide.tar.gz
  - export PATH=$PATH:/tmp/glide/${GLIDE_OS_ARCH}
env:
  - TEST_DIR=go_pinger/api
  - TEST_DIR=go_pinger/request
  - TEST_DIR=annotations
  - TEST_DIR=annotations/mockery
  - TEST_DIR=loogo
  - TEST_DIR=util/time
  - TEST_DIR=util/collections
  - TEST_DIR=follow_along/svc
script:
  - cd $TEST_DIR && glide install && go test -v
