version: '2.1'
services:
  supervisor:
    image: lukewendling/supervisor:1
    hostname: supervisor
    environment:
      - GIN_MODE=release
      - DB_HOST=172.17.0.1
      - PORT=3004
    ports:
      - "3004:3004"
    volumes:
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - .:/app
      - ./request/conf.toml:/app/request/conf.toml
