FROM ubuntu:16.04

# https://github.com/docker/docker/issues/4032
ARG DEBIAN_FRONTEND=noninteractive
ENV TERM=xterm

ARG BIN_NAME

RUN \
  apt-get update && \
  apt-get install -y \
    ca-certificates \
    supervisor
  
RUN \
  rm -rf /var/lib/apt/lists/* && \
  sed -i 's/^\(\[supervisord\]\)$/\1\nnodaemon=true/' /etc/supervisor/supervisord.conf

VOLUME ["/etc/supervisor/conf.d"]

ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

COPY bin/$BIN_NAME $GOPATH/bin
RUN ln -s $GOPATH/bin/$BIN_NAME $GOPATH/bin/go_app 

COPY supervisord.conf /etc/supervisor

WORKDIR /etc/supervisor/conf.d

ENTRYPOINT ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
